# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: about
    weight: 20
  - name: Projects
    url: internet-access
    weight: 30
  - name: Internet Access
    url: internet-access
    parent: Projects
    weight: 31
  - name: Digital Literacy
    url: digital-literacy
    parent: Projects
    weight: 32
  - name: IT Labs
    url: it-labs
    parent: Projects
    weight: 33
  - name: Solar Lanterns
    url: solar-lanterns
    parent: Projects
    weight: 34
  - name: Gallery
    url: gallery
    weight: 40
  - name: Contact
    url: contact
    weight: 50
